name: Keep Backend Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend to keep it alive
        run: curl -s "https://tutora-1.onrender.com" > /dev/null
